### ISSUE TITLE
Token models don't have chain_id attribute in responses

### ISSUE THREAD

**Issue by iouae** [dex-guru/dg-sdk-python#6]
[Merged](https://github.com/dex-guru/dg-sdk-python/pull/3), but should be fixed, if endpoint wouldn't get `chain_id` attribute in responses.

**Comment by evahteev** [comment]
@iouae Thanks for the commit. I've checked using the latest version https://pypi.org/project/dexguru-sdk/#history. Inventory/finance are returning chain_ids:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/17609011/217657085-b259318d-32fa-429b-90c2-a182cfa8f5c2.png">

**Comment by iouae** [comment]
> @iouae Thanks for the commit. I've checked using the latest version https://pypi.org/project/dexguru-sdk/#history. Inventory/finance are returning chain_ids:
>
@evahteev Thank you. Check this out.
` pytest -k 'test_get_token_market_history'`

**Comment by evahteev** [comment]
@iouae should be fine now
